-- STATUS-001: Persist real heartbeat history for VPS probes and status endpoints.
create table if not exists public.status_probe_heartbeats (
  id bigint generated by default as identity primary key,
  probe_id text not null,
  label text not null,
  region text,
  status text not null default 'unknown',
  summary text,
  reported_at timestamptz not null,
  received_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists idx_status_probe_heartbeats_probe_time
  on public.status_probe_heartbeats (probe_id, reported_at desc);

create index if not exists idx_status_probe_heartbeats_status_time
  on public.status_probe_heartbeats (status, reported_at desc);

create table if not exists public.status_endpoint_heartbeats (
  id bigint generated by default as identity primary key,
  endpoint_id text not null,
  label text not null,
  status text not null default 'unknown',
  summary text,
  checked_at timestamptz not null,
  response_ms integer,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_status_endpoint_heartbeats_endpoint_time
  on public.status_endpoint_heartbeats (endpoint_id, checked_at desc);

create index if not exists idx_status_endpoint_heartbeats_status_time
  on public.status_endpoint_heartbeats (status, checked_at desc);

create table if not exists public.status_alert_state (
  target_type text not null,
  target_id text not null,
  label text not null,
  status text not null default 'unknown',
  summary text,
  last_notified_status text,
  last_changed_at timestamptz not null default now(),
  last_notified_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (target_type, target_id)
);

create index if not exists idx_status_alert_state_status
  on public.status_alert_state (status);

alter table public.status_probe_heartbeats enable row level security;
alter table public.status_endpoint_heartbeats enable row level security;
alter table public.status_alert_state enable row level security;

revoke all on table public.status_probe_heartbeats from anon;
revoke all on table public.status_probe_heartbeats from authenticated;
revoke all on table public.status_endpoint_heartbeats from anon;
revoke all on table public.status_endpoint_heartbeats from authenticated;
revoke all on table public.status_alert_state from anon;
revoke all on table public.status_alert_state from authenticated;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant select, insert, update, delete on table public.status_probe_heartbeats to service_role;
    grant select, insert, update, delete on table public.status_endpoint_heartbeats to service_role;
    grant select, insert, update, delete on table public.status_alert_state to service_role;
    grant usage, select on sequence public.status_probe_heartbeats_id_seq to service_role;
    grant usage, select on sequence public.status_endpoint_heartbeats_id_seq to service_role;
  end if;
end;
$$;
